name: build and test CI workflow

on: [push]

env:

  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"

  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Set up JDK 14

      uses: actions/setup-java@v3

      with:

        distribution: 'adopt'

        java-version: '14'

    - name: Build project with Maven

      run: mvn -B compile --file pom.xml

  verify-and-package:

    needs: build

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Set up JDK 14

      uses: actions/setup-java@v3

      with:

        distribution: 'adopt'

        java-version: 14

    - name: Run all defined tests and generate war with Maven

      run: mvn -B verify --file pom.xml

    -

        name: Login to GHCR.IO

        uses: docker/login-action@v2

        with:

          registry: ghcr.io

          username: "victoriadecabo"

          password: ${{ secrets.PAT }}

    -

        name: Build and push

        uses: docker/build-push-action@v3

        with:

          context: .

          push: true

          tags: ghcr.io/victoriadecabo/tos:latest

